### ISSUE TITLE
Feature request: Collapsible Sections

### ISSUE THREAD

**Issue by miraclx** [structure-codes/vscode-tree-language#1]
Needed to manually diff two long blobs of trees, and this just makes it so much easier. Thanks.

So, here's a feature request, can you add support for collapsible sections?

VS Code calls this `Folding` https://code.visualstudio.com/docs/editor/codebasics#_folding

Maybe this is already on the roadmap, and if so, amazing, can't wait.. Anyways, thanks again!

**Comment by Hacksore** [comment]
Shipped 📦 with `v0.0.4`

**Comment by miraclx** [comment]
🙌🏽

**Comment by Hacksore** [comment]
All the hard work goes to @alex-oser 😅

**Comment by miraclx** [comment]
Nice work. Just tested it. Small nit though, everytime I open VS Code, it opens the `example.tree` debug file.

https://github.com/structure-codes/vscode-tree-language/blob/318381bfb781333996433025ff23812ad23c57c6/src/extension.ts#L25

Is this meant to default to false instead?

https://github.com/structure-codes/vscode-tree-language/blob/318381bfb781333996433025ff23812ad23c57c6/src/extension.ts#L9

**Comment by alex-oser** [comment]
Yeah 😬 Already pushing a v0.0.5 now

**Comment by miraclx** [comment]
Noticed this works exclusively for trees composed with tabs

https://github.com/structure-codes/vscode-tree-language/blob/debc8a4e74e0e112b50f3e8e946047195ced2b72/src/tree.ts#L2

The [`tree(1)`](https://linux.die.net/man/1/tree) command (on my machine, at least) swaps out tab for `   ` = `ascii:[ 160, 160, 32 (space) ]`

And [`cargo-tree(1)`](https://doc.rust-lang.org/cargo/commands/cargo-tree.html), for example, uses three spaces.

Tried building something that was spacing agnostic, and I came up with:

```js
const getNumberOfTabs = (line: string) => {
  let tabs;
  if ((tabs = line.match(/(.*)[├└]──/))) {
    return (tabs[1].match(/│/g) || []).length;
  }
  return 0;
};
```

But unfortunately, it doesn't cover this case 🤷🏽:

```
└── tarkah  # ✅ (tabs: 0)
    └── tickrs  # ❌ (tabs: 0)
```

Any solutions here?

**Comment by alex-oser** [comment]
Agreed it would be great to support any indentation format. Maybe we could achieve this by looking for the first line that is a child and extracting the tab character from there.

So I think the possible first children are:
```
│   ├── 
│   └── 
    ├── 
    └── 
```
We'd search for the first line that starts with any of these and extract the whitespace as the tab character to use. Wouldn't work if you have multiple types of tabs throughout the file though.

If we try a universal solution, we might run into a situation where someone uses 2 spaces as a tab and another uses 3. In that case we wouldn't be able to tell if 6 spaces means 2 or 3 tabs.

**Comment by miraclx** [comment]
Exactly.. I thought about those cases and I think the way out for parsing a tree is to, well.. treat it as a tree.. so, parents parse their children, and we work our way up the root. That way, we avoid dealing with indentation discrepancies.

I was already implementing this, but I couldn't figure out where `console.log` gets logged 🤷🏽 which makes it hard to debug. So I came here instead to report.

**Comment by alex-oser** [comment]
If you're debugging in vscode you can view the console by doing **Help > Toggle Developer Tools**. It's built on electron so we get all the chromium debug tools
