### ISSUE TITLE
Folding different tree lengths

### ISSUE THREAD

**Issue by GWeidmann** [structure-codes/vscode-tree-language#14]
I really like this tool for working with long windows-tree files (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tree).

It works amazingly but under one condition: The tree has to be exactly this: `├──`, so `├ + ─ + ─`.
The windows tree command generates trees with a length of 4, so `├───` = `├ + ─ + ─ + ─`.
So you have to search-replace the whole file to make the tool work.

Could you make a setting to let me specify the tree length or - at best - accept all different lengths and just search for `├ + ─`?

**Comment by Hacksore** [comment]
@GWeidmann one possible solution is to use `@structure-codes/cli` which gives you the `struct` util that might get you by.

More info here about the cli can be found here.
https://github.com/structure-codes/cli

**Comment by alex-oser** [comment]
I think we could easily update that regex to look for `/├─+/` instead of just `/├──/` when parsing. I think I have even seen some other tree formats with only 1 hyphen for example and this would work for that case as well. Will take a look at it.

**Comment by GWeidmann** [comment]
> @GWeidmann one possible solution is to use `@structure-codes/cli` which gives you the `struct` util that might get you by.
> 
> More info here about the cli can be found here. https://github.com/structure-codes/cli

It's just not possible to install some not necessary cli tool on our production server. I will not get permission for this.


> I think we could easily update that regex to look for `/├─+/` instead of just `/├──/` when parsing. I think I have even seen some other tree formats with only 1 hyphen for example and this would work for that case as well. Will take a look at it.

That would be awesome, thanks

**Comment by alex-oser** [comment]
I was playing around with this, is this what the output looks like for you when you run the command? It seems to be folding _decently_ for me with the current extension. Unfortunately I am not sure I will be able to get it to fold perfectly though since we are more targeting the Linux style trees.

Not folded
![image](https://user-images.githubusercontent.com/23581316/159206170-dba97130-1881-4fa4-8ad7-8ada536f09fd.png)

Folded
![image](https://user-images.githubusercontent.com/23581316/159206314-63e793a1-fd0d-4911-a704-810e3ac165b6.png)

**Comment by GWeidmann** [comment]
Hard to tell, it folds sometimes weird with and without files. I tried to figure out what the problem is but have not really found a solution.

From your second screenshot you can also see that api is not folding correctly.

Can I use [the struct files](https://github.com/structure-codes/cli) without installing it, so just placing it in a folder and executing it right there? This would probably also solve my problem.

**Comment by alex-oser** [comment]
One thing you could try would be packaging the module locally (on your computer) with a tool like [pkg](https://www.npmjs.com/package/pkg). This would let you create an executable with the Node runtime built in. Then you could use that in any other environment.

1. Clone repo
2. `npm install`
3. `npm run build`
4. `npx pkg dist/index.js -o struct.exe -t latest-win`

**Comment by GWeidmann** [comment]
Thanks I will try this the next time I need this functionality. At the moment I have used workarounds with manual steps.
