### ISSUE TITLE
[FR] Breadcrumb Support

### ISSUE THREAD

**Issue by ACH1980** [structure-codes/vscode-tree-language#2]
In addition to #1 Support for the Breadcrumb Trail would be nice.

**Comment by ACH1980** [comment]
Sorry, my fault, I thought it should be for directory trees saved into .tree files

**Comment by Hacksore** [comment]
@ACH1980 did you mean to close this?

**Comment by alex-oser** [comment]
Still seems like a good idea, but unsure exactly which vscode API controls building breadcrumbs. From some digging seemed like it may be: https://code.visualstudio.com/api/references/vscode-api#languages.registerDocumentSymbolProvider but need to look more
