### ISSUE TITLE
Folding is not working

### ISSUE THREAD

**Issue by shpoont** [structure-codes/vscode-tree-language#3]
I just installed the latest version of the extension, .tree files do not offer folding option in the VSCode UI.

**Comment by Hacksore** [comment]
@shpoont I was seeing the same thing and an uninstall and reinstall fixed it for me. Could you give that a try and report back?

@alex-oser does have some changes to make folding better but this might be a weird scenario where something borked the foldingProvider.

**Comment by alex-oser** [comment]
In the previous version folding only worked with tab characters. It should now be able to figure out what character you are using for spacing and still work. Let me know if that fixes it!

**Comment by Hacksore** [comment]
I think this is the issue 😅.
@alex-oser 

```log
mainThreadExtensionService.ts:95 Activating extension 'CTC.vscode-tree-extension' failed: Cannot find module 'nanoid'
Require stack:
- c:\Users\seanb\.vscode\extensions\ctc.vscode-tree-extension-0.0.6\out\tree.js
- c:\Users\seanb\.vscode\extensions\ctc.vscode-tree-extension-0.0.6\out\foldingProvider.js
- c:\Users\seanb\.vscode\extensions\ctc.vscode-tree-extension-0.0.6\out\extension.js
- c:\Users\seanb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\seanb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\seanb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

**Comment by alex-oser** [comment]
Ok well it seems like it's working in WSL but not in Windows - will try to fix soon :)

**Comment by alex-oser** [comment]
Just pushed another fix that is working for me now - issue was with eol characters and the regex we were using
